### ISSUE TITLE
Link to Svelte Blog for 2024

### ISSUE THREAD

**Issue by mgrubinger** [svelte-society/advent-of-svelte#23]
Hi,

I just noticed the link on https://advent.sveltesociety.dev/2024 does not yet point to the blog post for 2024 https://svelte.dev/blog/advent-of-svelte

advent.sveltesociety.dev is the top search result for "advent of svelte" for me, so a link over to the blog would make an easier journey.

Thank you!

**Comment by mgrubinger** [comment]
Seems fixed in ad95bc862d65adbccd9d5ece35130a47ddbd1efc
closing

**Comment by ghostdevv** [comment]
Oops only just saw this, thanks for the issue!
